### ISSUE TITLE
feat: Implement pre-push hooks to prevent CI failures

### ISSUE THREAD

**Issue by barde** [barde/phialoastro#107]
## Problem Statement

Our CI pipeline occasionally fails after code is pushed, leading to wasted time and resources. Currently, developers are instructed to run `npm run lint` and `npm run typecheck` commands that don't exist in the project, and there are no automated pre-push checks to catch issues before they reach CI.

### Current Issues:
1. **Missing commands referenced in CLAUDE.md**: `npm run lint` and `npm run typecheck` don't exist
2. **No pre-push validation**: Developers can push code that fails basic checks
3. **CI failures are discovered late**: Issues that could be caught locally are only found after pushing
4. **No code quality enforcement**: No linting or formatting tools configured

## Proposed Solution

Implement a comprehensive pre-push hook system using modern tooling to catch issues before they reach CI.

### 1. Tool Selection: Lefthook

After researching alternatives (Husky, pre-commit, simple-git-hooks), **Lefthook** is recommended because:
- **Performance**: Written in Go, supports parallel execution
- **Flexibility**: YAML-based configuration, easy to customize
- **Monorepo support**: Better suited for potential future growth
- **Active development**: 5,852 GitHub stars, regular updates

### 2. Pre-Push Checks Implementation

Create a layered approach to validation:

#### **Quick Pre-Commit Checks** (< 5 seconds):
- File size validation (no files > 5MB)
- Prohibited file type detection
- Basic syntax validation

#### **Comprehensive Pre-Push Checks** (< 2 minutes):
```yaml
# .lefthook.yml
pre-push:
  parallel: true
  commands:
    clean:
      run: ./scripts/clean-project.sh
    typecheck:
      run: cd phialo-design && npx astro check
    test:
      run: cd phialo-design && pnpm run test:run
    build:
      run: cd phialo-design && pnpm run build
    file-size:
      run: |
        large_files=$(find . -size +5M -not -path "./node_modules/*" -not -path "./.git/*")
        if [ -n "$large_files" ]; then
          echo "Error: Large files detected:"
          echo "$large_files"
          exit 1
        fi
```

#### **ESLint Configuration**
```json
// package.json additions
"scripts": {
  "lint": "eslint . --ext .js,.jsx,.ts,.tsx,.astro",
  "lint:fix": "eslint . --ext .js,.jsx,.ts,.tsx,.astro --fix",
  "typecheck": "astro check",
  "pre-push": "pnpm run typecheck && pnpm run lint && pnpm run test:pr"
}
```

#### **Prettier Configuration**
```json
// .prettierrc
{
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "printWidth": 100,
  "plugins": ["prettier-plugin-astro"],
  "overrides": [
    {
      "files": "*.astro",
      "options": {
        "parser": "astro"
      }
    }
  ]
}
```

#### Phase 1: Foundation (Week 1)
- [ ] Install and configure Lefthook
- [ ] Add missing `typecheck` script to package.json
- [ ] Create basic pre-push hooks for existing checks
- [ ] Update CLAUDE.md with correct commands

#### Phase 2: Code Quality (Week 2)
- [ ] Set up ESLint with Astro plugin
- [ ] Configure Prettier with Astro support
- [ ] Add lint and format scripts
- [ ] Integrate into pre-push hooks

#### Phase 3: Advanced Checks (Week 3)
- [ ] Add security scanning (detect-secrets)
- [ ] Implement selective test running for changed files
- [ ] Add branch protection rules
- [ ] Performance optimization for hooks

#### **Emergency Bypass**
- Always allow `git push --no-verify` for hotfixes
- Document when bypassing is acceptable
- Add bypass detection to CI for accountability

#### **Performance Targets**
- Pre-commit hooks: < 5 seconds
- Pre-push hooks: < 2 minutes
- Provide clear progress indicators

#### **Incremental Adoption**
- Start with opt-in hooks
- Gather team feedback
- Make mandatory after stabilization

### 6. Success Metrics

- **Reduction in CI failures**: Target 80% reduction in preventable failures
- **Developer satisfaction**: Survey after 1 month
- **Time saved**: Track CI minutes saved by catching issues locally
- **Code quality**: Monitor ESLint violation trends

## Alternative Approaches Considered

1. **Husky**: More popular but heavier, requires postinstall scripts
2. **Pre-commit**: Python-based, better for mixed-language projects
3. **Native Git hooks**: Too manual, hard to maintain consistency
4. **CI-only approach**: Too slow, wastes resources

## References

- [Lefthook Documentation](https://github.com/evilmartians/lefthook)
- [Git Hooks Best Practices](https://www.atlassian.com/git/tutorials/git-hooks)
- [Astro ESLint Plugin](https://github.com/ota-meshi/eslint-plugin-astro)

## Tasks

- [ ] Research and document team preferences for code style
- [ ] Create RFC for ESLint/Prettier rules
- [ ] Implement Phase 1 of the plan
- [ ] Create documentation for hook usage
- [ ] Add hook performance monitoring

## Questions for Discussion

1. Should we enforce hooks for all developers or make them opt-in initially?
2. What should be our ESLint rule severity (error vs warning)?
3. Should we add commit message linting as well?
4. Do we need different hooks for different branches (main vs feature)?

/cc @team 
Labels: enhancement, developer-experience, ci-cd
