### ISSUE TITLE
Optimize PR Test Run Times - Reduce from 30-40min to 10-15min

### ISSUE THREAD

**Issue by barde** [barde/phialoastro#77]
## 🎯 Objective

Optimize GitHub Actions PR test workflow to reduce execution time from 30-40 minutes to 10-15 minutes while maintaining test quality and coverage.

### Test Execution Breakdown
- **Unit Tests**: ~2-3 minutes
- **Build Step**: ~1-2 minutes
- **E2E Tests**: ~15-20 seconds × 80 scenarios (sequential) = 20-27 minutes
- **Total Runtime**: ~30-40 minutes

#### 1. Single Node Version Testing
Use the current Node version that the project is already using - no need for matrix testing across multiple versions.

#### 2. Sequential E2E Execution
```typescript
// playwright.config.ts
workers: process.env.CI ? 1 : undefined
```
- Forces 80 test scenarios to run sequentially
- Major bottleneck in test pipeline

#### 3. Optimized Browser Coverage
Keep browser tests but reduce to:
- iOS (Safari/WebKit)
- One Android use case (Chrome)
- This covers the essential mobile platforms efficiently

#### 4. No Conditional Testing
- All tests run on every PR regardless of changes
- No path-based filtering implemented

### 1. Implement Path-Based Conditional Testing (Highest Impact)

**Add to `.github/workflows/pr-tests.yml`:**
```yaml
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      tests: ${{ steps.filter.outputs.tests }}
      e2e: ${{ steps.filter.outputs.e2e }}
      config: ${{ steps.filter.outputs.config }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'src/**'
              - 'public/**'
            tests:
              - 'tests/**'
              - '**/*.test.ts'
              - '**/*.test.tsx'
            e2e:
              - 'tests/e2e/**'
              - 'playwright.config.ts'
            config:
              - '*.config.*'
              - 'package.json'
              - 'pnpm-lock.yaml'

  test:
    needs: changes
    if: |
      needs.changes.outputs.frontend == 'true' || 
      needs.changes.outputs.tests == 'true' || 
      needs.changes.outputs.config == 'true'
    # ... rest of test job
```

### 2. Simplify Test Configuration

**Use current Node version only:**
```yaml
strategy:
  matrix:
    node-version: [20.x]  # Or whatever version the project currently uses
```

**Optimize browser matrix to iOS + one Android:**
```typescript
// playwright.config.ts
projects: [
  { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  { name: 'firefox', use: { ...devices['Desktop Firefox'] } },
  { name: 'webkit', use: { ...devices['Desktop Safari'] } },
  { name: 'Mobile Safari', use: { ...devices['iPhone 12'] } }, // iOS
  { name: 'Mobile Chrome', use: { ...devices['Pixel 5'] } },   // Android
]
```

### 3. Enable Test Parallelization

**E2E parallel execution:**
```typescript
// playwright.config.ts
export default defineConfig({
  workers: process.env.CI ? 4 : undefined, // Changed from 1 to 4
  fullyParallel: true,
})
```

**Vitest sharding for unit tests:**
```yaml
test:
  strategy:
    matrix:
      shard: [1, 2, 3, 4]
  steps:
    - name: Run tests
      run: pnpm test:run -- --shard=${{ matrix.shard }}/4 --reporter=blob
```

### 4. Implement Smart Caching

**Cache Playwright browsers:**
```yaml
- name: Cache Playwright browsers
  uses: actions/cache@v4
  with:
    path: ~/.cache/ms-playwright
    key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
```

**Cache build artifacts:**
```yaml
- name: Cache build outputs
  uses: actions/cache@v4
  with:
    path: |
      phialo-design/dist
      phialo-design/.astro
    key: ${{ runner.os }}-build-${{ hashFiles('src/**', 'package.json') }}
```

### 5. Separate Build Job

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20  # Use current project version
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: phialo-design/dist

  test:
    needs: build
    # Download and use build artifacts
```

### Phase 1: Quick Wins (1-2 days)
- [ ] Use single Node version (current project version)
- [ ] Enable E2E parallelization (workers: 4)
- [ ] Add Playwright browser caching

### Phase 2: Path Filtering (2-3 days)
- [ ] Implement dorny/paths-filter
- [ ] Configure conditional job execution
- [ ] Test with various PR scenarios

### Phase 3: Advanced Optimization (3-4 days)
- [ ] Implement Vitest sharding
- [ ] Separate build job with artifact sharing
- [ ] Optimize browser matrix to iOS + Android only
- [ ] Add build output caching

### Phase 4: Monitoring & Tuning (ongoing)
- [ ] Track workflow execution times
- [ ] Fine-tune worker counts
- [ ] Adjust path filters based on usage

### Performance Improvements
- **Unit Tests**: 6-9 min → 2-3 min (single version + parallel sharding)
- **Build**: 3-6 min → 1-2 min (single build)
- **E2E Tests**: 20-27 min → 5-7 min (parallel + reduced browsers)
- **Total**: 30-40 min → 10-15 min (60-70% reduction)

### Additional Benefits
- Faster PR feedback loop
- Reduced GitHub Actions usage costs
- More efficient resource utilization
- Better developer experience

## 🔍 Success Metrics

1. **Primary**: Average PR test runtime < 15 minutes
2. **Secondary**: 
   - P95 test runtime < 20 minutes
   - No increase in flaky test rate
   - Maintain 100% critical path coverage

## 🏷️ Labels
- `enhancement`
- `ci/cd`
- `developer-experience`

## 🔗 Related Issues
- #64 - Mandatory test requirements for PRs
- #69 - PR test workflow implementation
