### ISSUE TITLE
Implement Ephemeral Preview Environments with Automatic Cleanup

### ISSUE THREAD

**Issue by barde** [barde/phialoastro#99]
# Implement Ephemeral Preview Environments with Automatic Cleanup

## Problem Statement

Currently, the preview deployment setup has the following limitations:
- Uses a single shared preview environment (`phialo-design-preview`) that gets overwritten with each PR
- No automatic cleanup when PRs are closed or merged
- No isolation between different PR previews
- No clear separation between PR previews and post-merge staging

## Proposed Solution

Implement ephemeral preview environments that:
1. Create unique preview URLs for each PR using Cloudflare's provided workers.dev domains (e.g., `phialo-pr-123.meise.workers.dev`)
2. Automatically delete the preview when the PR is closed or merged
3. Keep the existing preview environment (`phialo-design-preview`) as a post-merge deployment that always builds from master
4. Enable manual deployments for testing specific branches when needed

#### 1.1 Cloudflare API Permissions
Update the `CLOUDFLARE_API_TOKEN` with the following permissions:
- [ ] **Account permissions ONLY (no zone permissions needed for workers.dev):**
  - `Workers Scripts:Edit` - Create and delete workers
  - `Workers KV Storage:Edit` - Access KV namespaces (if needed by the app)

**Note**: Zone permissions are NOT required for workers.dev deployments. They are only needed when deploying to custom domains like phialo.de.

#### 1.2 Wrangler Configuration Updates
- [ ] Create a dynamic wrangler configuration template for ephemeral deployments
- [ ] Update existing `wrangler.toml` to support environment variables for worker names
- [ ] Keep the existing preview environment configuration unchanged

#### 2.1 Create Ephemeral Preview Workflow
Create `.github/workflows/ephemeral-preview.yml`:

```yaml
name: Ephemeral Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'workers/**'
      - 'phialo-design/**'
      - '.github/workflows/ephemeral-preview.yml'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci --prefix phialo-design
          npm ci --prefix workers
      
      - name: Build Astro site
        env:
          ENVIRONMENT: preview
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          cd phialo-design
          npm run build
      
      - name: Deploy to ephemeral environment
        id: deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cd workers
          # Create unique worker name
          WORKER_NAME="phialo-pr-${{ github.event.pull_request.number }}"
          
          # Deploy with dynamic worker name
          npx wrangler deploy \
            --name "$WORKER_NAME" \
            --compatibility-date "2024-01-01" \
            --no-bundle \
            --var ENVIRONMENT:preview \
            --var PR_NUMBER:${{ github.event.pull_request.number }}
          
          # Get the actual deployed URL from wrangler output
          # The URL will be in format: https://phialo-pr-123.meise.workers.dev
          PREVIEW_URL=$(npx wrangler deployments list --name "$WORKER_NAME" --json | jq -r '.[0].url // empty')
          
          # Fallback if the above doesn't work
          if [ -z "$PREVIEW_URL" ]; then
            # Get account subdomain from Cloudflare API
            SUBDOMAIN=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID" \
              -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
              -H "Content-Type: application/json" | jq -r '.result.name' | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
            PREVIEW_URL="https://${WORKER_NAME}.${SUBDOMAIN}.workers.dev"
          fi
          
          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT
      
      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const preview_url = '${{ steps.deploy.outputs.preview_url }}';
            const pr_number = context.issue.number;
            
            // Find and update existing comment or create new one
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('Preview Deployment')
            );
            
            const body = `## 🚀 Preview Deployment
            
            Your preview is ready at: ${preview_url}
            
            **Environment Details:**
            - Worker: \`phialo-pr-${pr_number}\`
            - Branch: \`${context.payload.pull_request.head.ref}\`
            - Commit: \`${context.sha.substring(0, 7)}\`
            
            This preview will be automatically deleted when the PR is closed or merged.`;
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr_number,
                body
              });
            }
```

#### 2.2 Create Cleanup Workflow
Create `.github/workflows/cleanup-preview.yml`:

```yaml
name: Cleanup Ephemeral Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Delete ephemeral worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          WORKER_NAME="phialo-pr-${{ github.event.pull_request.number }}"
          
          # Delete the worker
          npx wrangler delete "$WORKER_NAME" --force || true
      
      - name: Comment on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = context.issue.number;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: '## 🧹 Preview Cleaned Up\n\nThe ephemeral preview environment for this PR has been deleted.'
            });
```

#### 2.3 Update Existing Preview Workflow for Post-Merge
Update `.github/workflows/worker-preview.yml` to trigger on merge to master:

```yaml
name: Deploy Preview from Master

on:
  push:
    branches:
      - master
    paths:
      - 'workers/**'
      - 'phialo-design/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy to preview'
        required: false
        default: 'master'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'master' }}
      
      - name: Deploy to preview environment
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cd workers
          npm ci
          cd ../phialo-design
          npm ci
          npm run build
          cd ../workers
          npm run deploy:preview
```

#### 3.1 Update CLAUDE.md
Add the following section:

```markdown
## Deployment Environments

### Production (`phialo-design`)
- **URL**: https://phialo.de (custom domain)
- **Deployment**: Manual via GitHub UI or CLI
- **Branch**: Tagged releases only
- **Note**: Requires zone permissions for custom domain

### Preview (`phialo-design-preview`) 
- **URL**: https://phialo-design-preview.meise.workers.dev
- **Deployment**: Automatic on merge to master
- **Purpose**: Latest master branch preview
- **Manual Deploy**: Available via GitHub Actions UI

### Ephemeral PR Previews (`phialo-pr-{number}`)
- **URL**: https://phialo-pr-{number}.meise.workers.dev
- **Deployment**: Automatic on PR creation/update
- **Cleanup**: Automatic on PR close/merge
- **Purpose**: Isolated testing for each PR

## Cloudflare API Requirements

For workers.dev deployments (preview & PR environments):
- Account: Workers Scripts:Edit, Workers KV Storage:Edit

For custom domain deployment (production only):
- Account: Workers Scripts:Edit, Workers KV Storage:Edit
- Zone (phialo.de): Workers Routes:Edit, Zone:Read
```

#### 3.2 Update README.md
Add deployment information with correct URLs:

```markdown
## 🚀 Deployment

### Environments

- **Production**: [phialo.de](https://phialo.de) - Custom domain
- **Master Preview**: [phialo-design-preview.meise.workers.dev](https://phialo-design-preview.meise.workers.dev) - Latest master branch
- **PR Previews**: `https://phialo-pr-{number}.meise.workers.dev` - Ephemeral per PR

The site uses automatic deployments:
- PRs get temporary preview environments
- Master branch deploys to preview environment
- Production deployments are manual

### Deploy Commands

```bash
# Deploy to production (requires zone permissions)
npm run deploy

# Deploy to preview (workers.dev)
npm run deploy:preview
```

### Phase 4: Migration Plan

1. **Day 1**: Verify Cloudflare API token has correct account permissions (no zone permissions needed)
2. **Day 2**: Deploy ephemeral preview workflow and test with a dummy PR
3. **Day 3**: Deploy cleanup workflow and verify it works
4. **Day 4**: Update existing preview workflow for post-merge deployments
5. **Day 5**: Full testing and documentation updates

## Benefits

1. **Isolation**: Each PR gets its own preview environment
2. **Resource Efficiency**: Automatic cleanup prevents accumulation of unused workers
3. **Continuous Staging**: Preview environment always reflects latest master
4. **No Custom DNS**: Uses Cloudflare's provided workers.dev domains
5. **Simpler Permissions**: No zone permissions required for preview deployments

## Considerations

1. **Cloudflare Limits**: Check worker limits on the account (default is 30 workers)
2. **Worker Names**: Must be unique and follow Cloudflare naming conventions
3. **Security**: Ephemeral previews are publicly accessible (consider adding basic auth)
4. **API Rate Limits**: Cloudflare API has rate limits for worker operations
5. **Account Subdomain**: The workers.dev subdomain is `meise` for this account

## Success Criteria

- [ ] Each PR automatically gets a unique preview URL on workers.dev
- [ ] Preview environments are deleted within 5 minutes of PR closure
- [ ] Preview environment automatically updates on merge to master
- [ ] No manual intervention required for preview lifecycle
- [ ] Clear documentation differentiating workers.dev vs custom domain requirements

## Related Issues

- This builds upon the existing preview deployment system
- Enhances the current CI/CD pipeline
- Improves developer experience for testing changes

## Estimated Effort

- **API Permission Verification**: 15 minutes
- **Workflow Implementation**: 3-4 hours
- **Testing & Debugging**: 2-3 hours
- **Documentation**: 1 hour
- **Total**: ~1-2 days of work
